---
# The EPEL repo provides useful software packages that are not included in the official CentOS or Red Hat Enterprise Linux repositories
- name: Update EPEL Repository
  yum:
   name: https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
   state: present
  when: ansible_os_family == "RedHat" and {{ ansible_distribution_version.split('.')[0] }} == 7
  sudo: yes

# The Remi repo provides newer versions of the software in the core CentOS and Red Hat repos and depends on the EPEL repository
- name: Update Remi Repository CentOS 7 and Red Hat (RHEL) 7
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  when: ansible_os_family == "RedHat" and {{ ansible_distribution_version.split('.')[0] }} == 7
  sudo: yes

- name: Update server packages (RedHat)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"
  sudo: yes

- name: Update server packages (Debian)
  apt:
    upgrade: full
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Define system packages
  set_fact: system_packages = "{{ __system_packages || list }}"
  when: system_packages is not defined

- name: Install packages (RedHat)
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: system_packages
  when: ansible_os_family == "RedHat"
  sudo: yes

- name: Install packages (Debian)
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: system_packages
  when: ansible_os_family == "Debian"
  sudo: yes